# Generated by Django 3.2.9 on 2022-06-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cart',
            field=models.ManyToManyField(related_name='cart', to='commerce.Product'),
        ),
    ]
