# Generated by Django 3.2.9 on 2022-06-29 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_user_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Count', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcart', to='commerce.product')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernamecart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
