# Generated by Django 3.2.9 on 2022-06-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
