# Generated by Django 3.2.9 on 2022-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_rename_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Product_Count',
            field=models.IntegerField(default=0),
        ),
    ]
