# Generated by Django 3.2.9 on 2022-06-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_cartitem_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='ProductName',
        ),
    ]
