# Generated by Django 3.2.9 on 2022-06-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_cartitem_cartname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='CartName',
        ),
    ]
