# Generated by Django 3.2.9 on 2022-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_rename_product_count_cartitem_productcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ProductCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='Cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='commerce.Product'),
        ),
    ]
