# Generated by Django 3.2.9 on 2022-07-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20220629_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Number_added',
        ),
    ]
