# Generated by Django 3.2.9 on 2022-07-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_userr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
