# Generated by Django 3.2.9 on 2022-07-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_auto_20220709_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Total',
        ),
    ]
