# Generated by Django 3.2.9 on 2022-07-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_remove_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
