# Generated by Django 3.2.9 on 2022-07-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_cartitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Total',
            new_name='TotalPrice',
        ),
    ]
