# Generated by Django 3.2.9 on 2022-07-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_rename_total_cartitem_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='TotalPrice',
        ),
    ]
