# Generated by Django 3.2.9 on 2022-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_remove_cartitem_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='FinalCount',
            field=models.IntegerField(default=1),
        ),
    ]
