# Generated by Django 3.2.9 on 2022-12-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_auto_20220902_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Image',
            field=models.CharField(default='', max_length=700000),
        ),
        migrations.AlterField(
            model_name='product',
            name='SideImage_1',
            field=models.CharField(default='', max_length=700000),
        ),
        migrations.AlterField(
            model_name='product',
            name='SideImage_2',
            field=models.CharField(default='', max_length=700000),
        ),
        migrations.AlterField(
            model_name='product',
            name='SideImage_3',
            field=models.CharField(default='', max_length=700000),
        ),
    ]
